# Generated by Django 4.2 on 2023-04-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'валюту', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'операцию', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='operationtype',
            options={'verbose_name': 'тип операции', 'verbose_name_plural': 'Типы операций'},
        ),
    ]
