# Generated by Django 4.2 on 2023-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_category_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtype',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Тип операции'),
        ),
    ]
